version: '3.1'
services:
  teamspeak:
    image: ertagh/teamspeak3-server:latest-box-predownloaded
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TIME_ZONE: Asia/Karachi
    volumes:
      - "/data:/teamspeak/save/"